apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conv-temp
  template:
    metadata:
      labels:
        app: conv-temp
    spec:
      containers:
      - name: conv-temp
        image: pr02nl/conversao-temperatura:v2
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-conv-temp
spec:
  selector:
    app: conv-temp
  ports:
  - port: 8080
    nodePort: 30000
    # targetPort: <Target Port>
  type: NodePort